// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// addup_fp_left
SEXP addup_fp_left(int level, int start, int stop, int tp, int fn, int tn, int fp, double c0, double c1, double pi0);
RcppExport SEXP CVOC_addup_fp_left(SEXP levelSEXP, SEXP startSEXP, SEXP stopSEXP, SEXP tpSEXP, SEXP fnSEXP, SEXP tnSEXP, SEXP fpSEXP, SEXP c0SEXP, SEXP c1SEXP, SEXP pi0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type stop(stopSEXP);
    Rcpp::traits::input_parameter< int >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< int >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< int >::type tn(tnSEXP);
    Rcpp::traits::input_parameter< int >::type fp(fpSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type pi0(pi0SEXP);
    rcpp_result_gen = Rcpp::wrap(addup_fp_left(level, start, stop, tp, fn, tn, fp, c0, c1, pi0));
    return rcpp_result_gen;
END_RCPP
}
// addup_fp_right
SEXP addup_fp_right(int level, int start, int stop, int tp, int fn, int tn, int fp, double c0, double c1, double pi0);
RcppExport SEXP CVOC_addup_fp_right(SEXP levelSEXP, SEXP startSEXP, SEXP stopSEXP, SEXP tpSEXP, SEXP fnSEXP, SEXP tnSEXP, SEXP fpSEXP, SEXP c0SEXP, SEXP c1SEXP, SEXP pi0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type stop(stopSEXP);
    Rcpp::traits::input_parameter< int >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< int >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< int >::type tn(tnSEXP);
    Rcpp::traits::input_parameter< int >::type fp(fpSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type pi0(pi0SEXP);
    rcpp_result_gen = Rcpp::wrap(addup_fp_right(level, start, stop, tp, fn, tn, fp, c0, c1, pi0));
    return rcpp_result_gen;
END_RCPP
}
// addup_fn_left
SEXP addup_fn_left(int level, int start, int stop, int tp, int fn, int tn, int fp, double c0, double c1, double pi0);
RcppExport SEXP CVOC_addup_fn_left(SEXP levelSEXP, SEXP startSEXP, SEXP stopSEXP, SEXP tpSEXP, SEXP fnSEXP, SEXP tnSEXP, SEXP fpSEXP, SEXP c0SEXP, SEXP c1SEXP, SEXP pi0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type stop(stopSEXP);
    Rcpp::traits::input_parameter< int >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< int >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< int >::type tn(tnSEXP);
    Rcpp::traits::input_parameter< int >::type fp(fpSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type pi0(pi0SEXP);
    rcpp_result_gen = Rcpp::wrap(addup_fn_left(level, start, stop, tp, fn, tn, fp, c0, c1, pi0));
    return rcpp_result_gen;
END_RCPP
}
// addup_fn_right
SEXP addup_fn_right(int level, int start, int stop, int tp, int fn, int tn, int fp, double c0, double c1, double pi0);
RcppExport SEXP CVOC_addup_fn_right(SEXP levelSEXP, SEXP startSEXP, SEXP stopSEXP, SEXP tpSEXP, SEXP fnSEXP, SEXP tnSEXP, SEXP fpSEXP, SEXP c0SEXP, SEXP c1SEXP, SEXP pi0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type stop(stopSEXP);
    Rcpp::traits::input_parameter< int >::type tp(tpSEXP);
    Rcpp::traits::input_parameter< int >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< int >::type tn(tnSEXP);
    Rcpp::traits::input_parameter< int >::type fp(fpSEXP);
    Rcpp::traits::input_parameter< double >::type c0(c0SEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type pi0(pi0SEXP);
    rcpp_result_gen = Rcpp::wrap(addup_fn_right(level, start, stop, tp, fn, tn, fp, c0, c1, pi0));
    return rcpp_result_gen;
END_RCPP
}
