# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

addup_fp_left <- function(level, start, stop, tp, fn, tn, fp, c0, c1, pi0) {
    .Call('CVOC_addup_fp_left', PACKAGE = 'CVOC', level, start, stop, tp, fn, tn, fp, c0, c1, pi0)
}

addup_fp_right <- function(level, start, stop, tp, fn, tn, fp, c0, c1, pi0) {
    .Call('CVOC_addup_fp_right', PACKAGE = 'CVOC', level, start, stop, tp, fn, tn, fp, c0, c1, pi0)
}

addup_fn_left <- function(level, start, stop, tp, fn, tn, fp, c0, c1, pi0) {
    .Call('CVOC_addup_fn_left', PACKAGE = 'CVOC', level, start, stop, tp, fn, tn, fp, c0, c1, pi0)
}

addup_fn_right <- function(level, start, stop, tp, fn, tn, fp, c0, c1, pi0) {
    .Call('CVOC_addup_fn_right', PACKAGE = 'CVOC', level, start, stop, tp, fn, tn, fp, c0, c1, pi0)
}

